formatter: "markdown"

version: ">= 0.16.0"

header-from: main.tf

output:
  file: "README.md"
  mode: inject

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true