services:
  hava:
    image: ${HAVA_IMAGE}:${HAVA_VERSION}
    restart: always
    depends_on:
      - elastic
      - redis
    environment:
      ELASTICSEARCH_URL: "http://elastic:9200"
      REDIS_URL: "redis://redis:6379"
      LICENCE_FILE: /hava/hava.licence
    env_file:
      - /hava/hava.env
      - /hava/hava_db.env
    ports:
      - ${API_PORT}:${API_PORT} # web and api
      - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT} # websocket
    volumes:
      - hava:/hava/data
      - /hava/hava.licence:/hava/hava.licence:ro
      - /hava/ssl:/hava/ssl:ro

  elastic:
    image: elasticsearch:7.17.24
    restart: always
    environment:
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - http.max_content_length=500mb
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic:/usr/share/elasticsearch/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes: # volumes defined to ensure data survives a reboot of the container / VM
  elastic:
  hava:
  redis:
